'use strict';

const CROP_DATA = {
  rice:      { season:'Kharif (June – November)', N:'80–120 kg/ha', P:'40–60 kg/ha', K:'40–60 kg/ha', temperature:'20–35 °C', humidity:'70–90%', ph:'5.5–7.0', rainfall:'1000–2000 mm', soil_type:'Clay / Clay-loam (flooded paddy fields)', water_requirement:'Very High — 1200–2000 mm per season', growing_period:'110–150 days', tips:['Maintain 5–10 cm standing water during tillering.','Apply split doses of nitrogen: basal, tillering, panicle initiation.','Use certified disease-resistant varieties (IR64, BPT-5204, etc.).','Drain field 2 weeks before harvest to aid drying.'] },
  wheat:     { season:'Rabi (November – April)', N:'100–120 kg/ha', P:'50–60 kg/ha', K:'40–50 kg/ha', temperature:'10–25 °C', humidity:'50–70%', ph:'6.0–7.5', rainfall:'300–500 mm', soil_type:'Well-drained Loam / Sandy-loam', water_requirement:'Medium — 450–650 mm (4–6 irrigations)', growing_period:'100–150 days', tips:['Sow within the optimal window (Nov 1–15) to avoid terminal heat stress.','First irrigation (Crown Root Initiation) is the most critical.','Treat seeds with Thiram + Carboxin to prevent loose smut.','Apply Zinc sulphate (25 kg/ha) if deficiency symptoms appear.'] },
  maize:     { season:'Kharif (June – September)', N:'120–150 kg/ha', P:'60–80 kg/ha', K:'60–80 kg/ha', temperature:'18–32 °C', humidity:'55–75%', ph:'5.8–7.0', rainfall:'500–900 mm', soil_type:'Well-drained Sandy-loam to Clay-loam', water_requirement:'Medium — 500–800 mm', growing_period:'80–110 days', tips:['Apply 50% N + full P & K as basal; remaining N in 2 splits.','Ensure proper drainage — maize is highly sensitive to waterlogging.','Use hybrid seeds for 20–30% higher yield potential.','Critical stages: knee-high, tasselling, grain-filling.'] },
  cotton:    { season:'Kharif (April – November)', N:'100–150 kg/ha', P:'50–70 kg/ha', K:'50–70 kg/ha', temperature:'21–35 °C', humidity:'50–80%', ph:'6.0–8.0', rainfall:'500–1000 mm', soil_type:'Black cotton soil (Vertisol) / Deep loam', water_requirement:'Medium-High — 700–1200 mm', growing_period:'150–180 days', tips:['Adopt Bt-cotton varieties to reduce bollworm infestation.','Regular scouting for pink bollworm and whitefly.','Adopt drip irrigation to save 40% water.','Avoid excess N — leads to vegetative growth at cost of bolls.'] },
  sugarcane: { season:'Year-round (planted Oct–Mar, harvested 10–12 months later)', N:'150–180 kg/ha', P:'60–80 kg/ha', K:'100–120 kg/ha', temperature:'20–40 °C', humidity:'60–90%', ph:'6.0–7.5', rainfall:'1100–1500 mm', soil_type:'Deep well-drained Loam / Sandy-loam', water_requirement:'Very High — 1500–2500 mm per crop', growing_period:'10–18 months', tips:['Use disease-free sets / tissue-culture seedlings.','Drip fertigation can reduce water use by up to 40%.','Trash mulching retains soil moisture.','Harvest at correct maturity (Brix 18–20%).'] },
  millet:    { season:'Kharif (June – September)', N:'40–60 kg/ha', P:'20–40 kg/ha', K:'20–30 kg/ha', temperature:'25–35 °C', humidity:'40–60%', ph:'6.0–8.0', rainfall:'200–600 mm', soil_type:'Sandy / Sandy-loam (poor soils tolerated)', water_requirement:'Low — 200–400 mm (drought-tolerant)', growing_period:'60–90 days', tips:['Ideal for arid/semi-arid regions with unreliable rainfall.','Inter-crop with legumes to improve soil N.','One weeding at 15–20 DAS significantly improves yield.','Harvest when 80% of earheads turn straw-coloured.'] },
  barley:    { season:'Rabi (October – March)', N:'60–80 kg/ha', P:'30–40 kg/ha', K:'25–35 kg/ha', temperature:'7–25 °C', humidity:'45–65%', ph:'6.0–8.5', rainfall:'250–400 mm', soil_type:'Loamy / Sandy-loam (tolerates saline/alkaline)', water_requirement:'Low-Medium — 350–500 mm', growing_period:'90–120 days', tips:['Most suitable where wheat fails — tolerates salinity better.','Sow early (Oct) for malting barley.','Two irrigations (CRI + milking) are sufficient.','Blast seed with Tebuconazole to prevent loose smut.'] },
  groundnut: { season:'Kharif (June – September)', N:'20–30 kg/ha', P:'40–60 kg/ha', K:'40–60 kg/ha', temperature:'25–35 °C', humidity:'50–70%', ph:'6.0–7.5', rainfall:'500–700 mm', soil_type:'Well-drained Sandy-loam (free from stones)', water_requirement:'Medium — 500–700 mm', growing_period:'95–130 days', tips:['Apply gypsum (250–500 kg/ha) at flowering.','Inoculate seed with Rhizobium.','Avoid waterlogging at pegging and pod-filling stages.','Harvest when inner shell surface turns dark-coloured.'] },
  soybean:   { season:'Kharif (June – September)', N:'25–30 kg/ha (starter dose)', P:'60–80 kg/ha', K:'40–50 kg/ha', temperature:'20–30 °C', humidity:'60–80%', ph:'6.0–7.0', rainfall:'600–900 mm', soil_type:'Well-drained Clay-loam / Loam', water_requirement:'Medium — 450–700 mm', growing_period:'90–120 days', tips:['Inoculate seed with Bradyrhizobium japonicum.','Critical moisture: flowering and pod-fill.','Avoid deep sowing — 3–4 cm is optimal.','Excellent rotation crop.'] },
  potato:    { season:'Rabi / Spring (Oct–Jan or Jan–Mar)', N:'120–150 kg/ha', P:'80–100 kg/ha', K:'100–120 kg/ha', temperature:'10–25 °C', humidity:'60–80%', ph:'5.0–6.5', rainfall:'500–700 mm', soil_type:'Deep well-drained Sandy-loam / Loam', water_requirement:'Medium-High — 500–700 mm', growing_period:'70–120 days', tips:['Use certified seed tubers free from PVX, PVY, and PLRV.','Hill up rows at 30–40 DAS.','Watch for late blight — spray Mancozeb at first sign.','Harvest after vine senescence.'] },
  tomato:    { season:'Year-round with irrigation (best Sep–Feb)', N:'100–150 kg/ha', P:'60–80 kg/ha', K:'100–120 kg/ha', temperature:'15–30 °C', humidity:'50–70%', ph:'6.0–7.0', rainfall:'400–600 mm', soil_type:'Well-drained fertile Loam / Sandy-loam', water_requirement:'Medium-High — drip irrigation preferred', growing_period:'60–100 days from transplanting', tips:['Stake/trellis plants for better air circulation.','Drip fertigation improves water-use efficiency.','Monitor for Tuta absoluta — use pheromone traps.','Harvest at pink-to-red stage for transport.'] },
  sunflower: { season:'Kharif / Rabi (flexible)', N:'60–90 kg/ha', P:'40–60 kg/ha', K:'30–40 kg/ha', temperature:'18–35 °C', humidity:'40–70%', ph:'6.0–7.5', rainfall:'500–750 mm', soil_type:'Well-drained Sandy-loam to Clay-loam', water_requirement:'Medium — 400–600 mm', growing_period:'90–120 days', tips:['Aid pollination by introducing bee hives at flowering.','Foliar spray of Boron (0.2%) at bud stage.','Hand-pollination at 8–10 AM increases yield by 20–25%.','Harvest when back of head turns lemon-yellow.'] },
  pulses:    { season:'Rabi (October – March)', N:'20–25 kg/ha (starter)', P:'40–60 kg/ha', K:'20–30 kg/ha', temperature:'15–30 °C', humidity:'40–70%', ph:'6.0–8.0', rainfall:'300–600 mm', soil_type:'Well-drained Loam / Sandy-loam', water_requirement:'Low-Medium — 350–500 mm', growing_period:'90–120 days', tips:['Excellent rotation crop — fixes 40–200 kg N/ha.','Treat seed with Rhizobium + PSB.','One irrigation at pre-flowering stage improves pod set.','Harvest when 70–80% pods turn brown.'] },
  jute:      { season:'Kharif (March – June)', N:'60–80 kg/ha', P:'30–40 kg/ha', K:'30–40 kg/ha', temperature:'24–38 °C', humidity:'70–90%', ph:'6.0–7.5', rainfall:'1200–1800 mm', soil_type:'Alluvial / Loam', water_requirement:'High — 1200–1800 mm', growing_period:'100–120 days', tips:['Retting is critical — use slow-moving water for 10–15 days.','Harvest at 50% flowering for best fibre quality.','Dense sowing (6–7 kg seed/ha) improves fibre fineness.','Apply Azospirillum biofertiliser.'] },
};

module.exports = { CROP_DATA };
